### ISSUE TITLE
Any draft version of wasi-io?

### ISSUE THREAD

**Issue by lygstate** [WebAssembly/wasi-io#1]

**Comment by sunfishcode** [comment]
I've now posted a starting point here:

https://github.com/WebAssembly/wasi-io/pull/2

**Comment by lygstate** [comment]
Thanks

**Comment by sunfishcode** [comment]
https://github.com/WebAssembly/wasi-io/pull/4 is now a much more complete version of the I/O streams part of wasi-io.
