### ISSUE TITLE
Can pipe method have two results?

### ISSUE THREAD

**Issue by MediosZ** [WebAssembly/wasi-io#13]
According to [this line in witx crate](https://github.com/WebAssembly/WASI/blob/bac366c8aeb69cacfea6c4c04a503191bf1cede1/tools/witx/src/abi.rs#L374), a method can not have more than one result. However, [the pipe method](https://github.com/WebAssembly/wasi-io/blob/5d62e192ef53c3d969ba32f4485b293108d7bd55/standard/io/witx/io_streams.witx#L250) have two results. Is this valid or am I missing something?

**Comment by sunfishcode** [comment]
The wasi-io code here was written under the assumption that that line in the witx crate was a temporary restriction that would be lifted at some point.

However, with our experience from witx, the evolution of interface types, and the development of the component model, we've realized that what WASI really needs is a different kind of IDL and a different kind of tooling. This is now being realized in the new wit format, and the [wit-bindgen](https://github.com/bytecodealliance/wit-bindgen) tooling. The new tooling already has support for multiple return values, among many other features, and overall is much more capable than the witx tooling.

I'm currently in the process of putting together a plan for moving WASI as a whole to this new tooling, and figuring out how wasi-io fits into this.

**Comment by MediosZ** [comment]
I get it. Thanks for your quick response!
