### ISSUE TITLE
Non-blocking streams

### ISSUE THREAD

**Issue by badeend** [WebAssembly/wasi-io#25]
1. Streams have `subscribe-` functions. But `stream-error` has no EWOULDBLOCK equivalent indicator. How do stream consumers know when to call `subscribe-` ?
2. How does a stream know whether or not to use non-blocking semantics? Is it controlled from the parent resource (file, socket, ...). If so, doesn't that violate the intended separation of producers & consumers?

**Comment by sunfishcode** [comment]
I've been exploring a few different options here, and I'm now proposing to address this with #24: just make all streams non-blocking. An `EWOULDBLOCK` from the host would be surfaced as reading or writing 0 bytes.

Consumers that wish to block, such as wasi-libc functions that need to provide POSIX blocking semantics, can use a `poll-oneoff` call to block if they get 0 bytes from the initial `read` or `write`. That might be a common need, so I'm contemplating also adding explicit blocking functions as well, `blocking-read` and `blocking-write` and so on.

With this approach, the decision of whether to block or not would be up to the user of the stream, not up to the stream itself.

**Comment by badeend** [comment]
Oh, sorry. I didn't notice there was an PR already. Your explanation & the PR have fully answered my question. Thanks!
