### ISSUE TITLE
How to open a stream?

### ISSUE THREAD

**Issue by dannypsnl** [WebAssembly/wasi-io#43]
There have `read`, `skip`, `subscribe`, and `drop`, but I didn't find anyway to open anything as a stream. Am I missing something?

**Comment by pchickey** [comment]
Streams are a low level primitive used across many different interfaces. [Sockets](https://github.com/WebAssembly/wasi-sockets), [files](https://github.com/WebAssembly/wasi-filesystem), and [http bodies](https://github.com/WebAssembly/wasi-http) use these streams. And any wit interface you define and implement yourself can use them as well.
