### ISSUE TITLE
what's the purpose of `pollable.block`?

### ISSUE THREAD

**Issue by yamt** [WebAssembly/wasi-io#60]
`pollable.block` is documented as:
```
      /// This function is equivalent to calling `poll.poll` on a list
      /// containing only this pollable.
```

what's the point to have this redundant method?
what's wrong with always using `poll.poll`?

**Comment by pchickey** [comment]
We provide convenience methods on the streams resources for performing blocking reads, writes, and flushes. This is another convenience method. We found ourselves adding this method pretty frequently in library code, so its nice to have the bindings generate it for us.

**Comment by sunfishcode** [comment]
The question here seems answered; please reopen or file new issues if there are any further questions!
