### ISSUE TITLE
What is allowed to happen after `last-operation-failed` ?

### ISSUE THREAD

**Issue by badeend** [WebAssembly/wasi-io#83]
The docs for `stream-error::closed` read:

```
The stream is closed: no more input will be accepted by the stream.
A closed output-stream will return this error on all future operations.
```

Should the same apply for `stream-error::last-operation-failed` ?
I.e.: are errors final or are transient errors allowed?

**Comment by pchickey** [comment]
The intent was that all errors are final - we couldn't come up with a good story for why transient errors should be reported at all through the stream interfaces.

**Comment by badeend** [comment]
Okay. I've created a PR to clarify this: https://github.com/WebAssembly/wasi-io/pull/84
